
# Chapter 13: Machine learning techniques

### Importing the necessary packages

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import random as rd
rd.seed(0)

### Download and unzip dataset

In [4]:
#!/bin/bash
!curl -L -o /content/titanic-dataset.zip\
  https://www.kaggle.com/api/v1/datasets/download/yasserh/titanic-dataset

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 22564  100 22564    0     0  51560      0 --:--:-- --:--:-- --:--:--     0

In [5]:
# Unzip dataset
#!/bin/bash
!unzip /content/titanic-dataset.zip -d /content/

Archive:  /content/titanic-dataset.zip
  inflating: /content/Titanic-Dataset.csv

## 13.1 Loading and exploring the dataset

In [6]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU ARE WORKING ON A COLAB

url = "https://raw.githubusercontent.com/luisguiserrano/manning/master/Chapter_13_End_to_end_example/titanic.csv"
raw_data = pd.read_csv(url)
raw_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Next, we can explore the dataset.

In [7]:
# Examining the length of the dataset
print("The dataset has", len(raw_data), "rows")

The dataset has 891 rows

In [8]:
# Examining the columns in the dataset
print("Columns (features of the dataset)")
raw_data.columns

Columns (features of the dataset)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Examining the labels

In [9]:
# Examining the labels
print("Labels")
raw_data["Survived"]

Labels

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

Examining how many passengers survived

In [10]:
# Examining how many passengers survived
print(sum(raw_data['Survived']), 'passengers survived out of', len(raw_data))

342 passengers survived out of 891

In [11]:
# One can look at several columns together
raw_data[["Name", "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

## 13.2. Cleaning up the data

### Now, let's look at how many columns have missing data

In [12]:
raw_data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

The Cabin column is missing too many values to be useful. Let's drop it altogether.

In [13]:
raw_data['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [14]:
print("The Cabin column is missing", sum(raw_data['Cabin'].isna()), "values out of",len(raw_data['Cabin']))

The Cabin column is missing 687 values out of 891

### Exemine dataset after dropping Cabin feature (column)

In [15]:
preprocessed_data = raw_data.drop('Cabin', axis=1)

In [16]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

### Filling in missing data

Other columns such as Age or Embarked are missing some values, but they can still be useful.

In [17]:
preprocessed_data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

#### For the age column, let's fill in the missing values with the median of all ages.

In [18]:
median_age = raw_data["Age"].median()
median_age

28.0

In [19]:
preprocessed_data["Age"] = preprocessed_data["Age"].fillna(median_age)

In [20]:
rows_with_age_median = preprocessed_data[preprocessed_data['Age'] == median_age]
print(len(rows_with_age_median))

202

In [21]:
preprocessed_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

#### For the Embarked column, let's make a new category called 'U', for Unknown port of embarkment.

In [22]:
preprocessed_data["Embarked"] = preprocessed_data["Embarked"].fillna('U')

In [23]:
rows_with_embarked_u = preprocessed_data[preprocessed_data['Embarked'] == 'U']
rows_with_embarked_u

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,U
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,U

In [24]:
preprocessed_data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [25]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

### Save cleaned dataset for later use

In [26]:
preprocessed_data.to_csv('./clean_titanic_data.csv', index=None)

## 13.3 Manipulating the features

### Load cleaned dataset we stored in cleaning section

In [27]:
preprocessed_data = pd.read_csv('./clean_titanic_data.csv')
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

* One-hot encoding
* Binning
* Feature selection

## 13.3.1 One-hot encoding

#### One-hot encoding the gender feature

In [28]:
gender_columns = pd.get_dummies(preprocessed_data['Sex'], prefix='Sex')
print(gender_columns)
embarked_columns = pd.get_dummies(preprocessed_data["Embarked"], prefix="Embarked")
print(embarked_columns)

     Sex_female  Sex_male
0         False      True
1          True     False
2          True     False
3          True     False
4         False      True
..          ...       ...
886       False      True
887        True     False
888        True     False
889       False      True
890       False      True

[891 rows x 2 columns]
     Embarked_C  Embarked_Q  Embarked_S  Embarked_U
0         False       False        True       False
1          True       False       False       False
2         False       False        True       False
3         False       False        True       False
4         False       False        True       False
..          ...         ...         ...         ...
886       False       False        True       False
887       False       False        True       False
888       False       False        True       False
889        True       False       False       False
890       False        True       False       False

[891 rows x 4 columns]

#### Add One-hot encoded columns to data

In [29]:
preprocessed_data = pd.concat([preprocessed_data, gender_columns], axis=1)
preprocessed_data = pd.concat([preprocessed_data, embarked_columns], axis=1)

#### Remove Original columns (features)

In [30]:
preprocessed_data = preprocessed_data.drop(['Sex', 'Embarked'], axis=1)

In [31]:
preprocessed_data.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True,False,False,True,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False,True,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False,False,False,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True,False,False,True,False

### A rule of thumb for when to one-hot encode or not

In [32]:
class_survived = preprocessed_data[['Pclass', 'Survived']]

first_class = class_survived[class_survived['Pclass'] == 1]
second_class = class_survived[class_survived['Pclass'] == 2]
third_class = class_survived[class_survived['Pclass'] == 3]

print("In first class", sum(first_class['Survived'])/len(first_class)*100, "% of passengers survived")
print("In second class", sum(second_class['Survived'])/len(second_class)*100, "% of passengers survived")
print("In third class", sum(third_class['Survived'])/len(third_class)*100, "% of passengers survived")

In first class 62.96296296296296 % of passengers survived
In second class 47.28260869565217 % of passengers survived
In third class 24.236252545824847 % of passengers survived

In [33]:
categorized_pclass_columns = pd.get_dummies(preprocessed_data['Pclass'], prefix='Pclass')
preprocessed_data = pd.concat([preprocessed_data, categorized_pclass_columns], axis=1)
preprocessed_data = preprocessed_data.drop(['Pclass'], axis=1)

In [34]:
preprocessed_data.head()

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,False,True,False,False,True,False,False,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,True,False,True,False,False,False,True,False,False
2,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,True,False,False,False,True,False,True,False,False
4,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,False,True,False,False,True,False,False,False,True

## 13.3.3 Binning

### Split age feature into several different buckets

In [35]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]
categorized_age = pd.cut(preprocessed_data['Age'], bins)
preprocessed_data['Categorized_age'] = categorized_age
preprocessed_data = preprocessed_data.drop(["Age"], axis=1)

In [36]:
preprocessed_data.head()

,PassengerId,Survived,Name,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3,Categorized_age
0,1,0,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.2500,False,True,False,False,True,False,False,False,True,"(20, 30]"
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,71.2833,True,False,True,False,False,False,True,False,False,"(30, 40]"
2,3,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,7.9250,True,False,False,False,True,False,False,False,True,"(20, 30]"
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,53.1000,True,False,False,False,True,False,True,False,False,"(30, 40]"
4,5,0,"Allen, Mr. William Henry",0,0,373450,8.0500,False,True,False,False,True,False,False,False,True,"(30, 40]"

### Turn binned numerical feature (age) into categorical with One-hot endcoding

In [37]:
cagegorized_age_columns = pd.get_dummies(preprocessed_data['Categorized_age'], prefix='Categorized_age')
preprocessed_data = pd.concat([preprocessed_data, cagegorized_age_columns], axis=1)
preprocessed_data = preprocessed_data.drop(['Categorized_age'], axis=1)

In [38]:
preprocessed_data.head()

,PassengerId,Survived,Name,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,...,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,1,0,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.2500,False,True,False,...,False,True,False,False,True,False,False,False,False,False
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,71.2833,True,False,True,...,False,False,False,False,False,True,False,False,False,False
2,3,1,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,7.9250,True,False,False,...,False,True,False,False,True,False,False,False,False,False
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,53.1000,True,False,False,...,False,False,False,False,False,True,False,False,False,False
4,5,0,"Allen, Mr. William Henry",0,0,373450,8.0500,False,True,False,...,False,True,False,False,False,True,False,False,False,False

## 13.3.3 Feature selection

In [39]:
preprocessed_data = preprocessed_data.drop(['Name', 'Ticket', 'PassengerId'], axis=1)

In [62]:
preprocessed_data.head()

,Survived,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,...,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,0,1,0,7.2500,False,True,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
1,1,1,0,71.2833,True,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,7.9250,True,False,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
3,1,1,0,53.1000,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,0,0,0,8.0500,False,True,False,False,True,False,...,False,True,False,False,False,True,False,False,False,False

### Save cleaned dataset for later use

In [41]:
preprocessed_data.to_csv('./preprocessed_titanic_data.csv', index=None)

## 13.4 Training models

### Load pre-processed dataset we stored in previous sections

In [42]:
data = pd.read_csv('./preprocessed_titanic_data.csv')
data.head()

,Survived,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,...,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,0,1,0,7.2500,False,True,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
1,1,1,0,71.2833,True,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,7.9250,True,False,False,False,True,False,...,False,True,False,False,True,False,False,False,False,False
3,1,1,0,53.1000,True,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
4,0,0,0,8.0500,False,True,False,False,True,False,...,False,True,False,False,False,True,False,False,False,False

### 13.4.1 Features-labels split and train-validation split

#### Features-labels split

In [43]:
features = data.drop(["Survived"], axis=1)
labels = data["Survived"]

In [44]:
features.head()

,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,1,0,7.2500,False,True,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False
1,1,0,71.2833,True,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False
2,0,0,7.9250,True,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False
3,1,0,53.1000,True,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False,False
4,0,0,8.0500,False,True,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False

In [45]:
labels

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

#### Train-validation split

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
# remark: we fix random_state the end, to make sure we always get the same split
features_train, features_validation_test, labels_train, labels_validation_test = train_test_split(
    features, labels, test_size=0.4, random_state=100)

In [48]:
features_validation, features_test, labels_validation, labels_test = train_test_split(
    features_validation_test, labels_validation_test, test_size=0.5, random_state=100)

In [49]:
print(len(features_train))
print(len(features_validation))
print(len(features_test))
print(len(labels_train))
print(len(labels_validation))
print(len(labels_test))

534
178
179
534
178
179

### 13.4.2 Training different models on our dataset

We'll train four models with basic model:

* Logistic regression (perceptron)
* Decision tree
* Naive Bayes
* Support vector machine (SVM)

#### Logistic regression (perceptron)

In [63]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
lr_model.fit(features_train, labels_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

#### Decision tree

In [64]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(features_train, labels_train)

DecisionTreeClassifier()

#### Naive Bayes - Guassian Naive Bayes model

In [65]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(features_train, labels_train)

GaussianNB()

#### Support vector machine (SVM)

In [66]:
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(features_train, labels_train)

SVC()



---

We'll train three models with Ensemble techniques:

* Random forest
* Gradient boosted tree
* AdaBoost

#### Random forest (with Decision tree weak learners)

In [67]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
rf_model.fit(features_train, labels_train)

RandomForestClassifier()

#### Gradient boosted tree

In [68]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()
gb_model.fit(features_train, labels_train)

GradientBoostingClassifier()

#### AdaBoost

In [69]:
from sklearn.ensemble import AdaBoostClassifier

ab_model = AdaBoostClassifier()
ab_model.fit(features_train, labels_train)

AdaBoostClassifier()

#### XGboost

Rename feature (column) names for XGboost model

In [95]:
import re

def clean_col(col: str) -> str:
    col = str(col)
    # remove forbidden chars and parentheses, make it nice
    col = re.sub(r"[\[\]<>\(\)]", "", col)
    col = col.replace(" ", "_")
    return col

features_train_xgboost = features_train.rename(columns=clean_col)
features_validation_xgboost = features_validation.rename(columns=clean_col)
features_test_xgboost = features_test.rename(columns=clean_col)

In [85]:
from xgboost import XGBClassifier

xgboost_model = XGBClassifier()
xgboost_model.fit(features_train_xgboost, labels_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

#### Building and training the neural network

In [107]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# X: features_train (DataFrame), y: labels_train (0/1)
X_train = features_train.values.astype("float32")
X_val   = features_validation.values.astype("float32")
X_test  = features_test.values.astype("float32")

y_train = labels_train.astype("float32").values
y_val   = labels_validation.astype("float32").values
y_test  = labels_test.astype("float32").values

model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.1))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))  # single neuron for binary classification

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [108]:
# Neural Network training
nn_model = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_val, y_val),
    verbose=1
)

Epoch 1/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 5s 134ms/step - accuracy: 0.5343 - loss: 1.0381 - val_accuracy: 0.6348 - val_loss: 0.6718
Epoch 2/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6046 - loss: 1.0335 - val_accuracy: 0.7022 - val_loss: 0.6025
Epoch 3/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6465 - loss: 0.8149 - val_accuracy: 0.7135 - val_loss: 0.5690
Epoch 4/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6487 - loss: 0.9204 - val_accuracy: 0.7247 - val_loss: 0.5930
Epoch 5/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6864 - loss: 0.7118 - val_accuracy: 0.6742 - val_loss: 0.5900
Epoch 6/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6863 - loss: 0.6752 - val_accuracy: 0.7135 - val_loss: 0.5485
Epoch 7/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7244 - loss: 0.6106 - val_accuracy: 0.7247 - val_loss: 0.5391
Epoch 8/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6974 - loss: 0.7391 - val_accuracy: 0.7303 - val_loss: 0.5465
Epoch 9/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7359 - loss: 0.6053 - val_accuracy: 0.7135 - val_loss: 0.5522
Epoch 10/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7209 - loss: 0.6284 - val_accuracy: 0.7528 - val_loss: 0.5452
Epoch 11/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7363 - loss: 0.6438 - val_accuracy: 0.7416 - val_loss: 0.5352
Epoch 12/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7537 - loss: 0.5161 - val_accuracy: 0.7584 - val_loss: 0.5344
Epoch 13/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7372 - loss: 0.5567 - val_accuracy: 0.7697 - val_loss: 0.5387
Epoch 14/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7627 - loss: 0.5190 - val_accuracy: 0.7753 - val_loss: 0.5292
Epoch 15/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7903 - loss: 0.5328 - val_accuracy: 0.7697 - val_loss: 0.5333
Epoch 16/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7811 - loss: 0.5253 - val_accuracy: 0.7697 - val_loss: 0.5290
Epoch 17/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7629 - loss: 0.5415 - val_accuracy: 0.7640 - val_loss: 0.5277
Epoch 18/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.4756 - val_accuracy: 0.7640 - val_loss: 0.5368
Epoch 19/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7607 - loss: 0.4913 - val_accuracy: 0.7640 - val_loss: 0.5324
Epoch 20/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7916 - loss: 0.4591 - val_accuracy: 0.7697 - val_loss: 0.5344
Epoch 21/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7918 - loss: 0.4801 - val_accuracy: 0.7697 - val_loss: 0.5289
Epoch 22/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8109 - loss: 0.4442 - val_accuracy: 0.7921 - val_loss: 0.5341
Epoch 23/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8068 - loss: 0.4707 - val_accuracy: 0.7697 - val_loss: 0.5410
Epoch 24/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.5330 - val_accuracy: 0.7360 - val_loss: 0.5378
Epoch 25/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7767 - loss: 0.5284 - val_accuracy: 0.7753 - val_loss: 0.5555
Epoch 26/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8014 - loss: 0.4293 - val_accuracy: 0.7753 - val_loss: 0.5275
Epoch 27/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8027 - loss: 0.4623 - val_accuracy: 0.7697 - val_loss: 0.5324
Epoch 28/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4868 - val_accuracy: 0.7809 - val_loss: 0.5509
Epoch 29/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8422 - loss: 0.4196 - val_accuracy: 0.7528 - val_loss: 0.5312
Epoch 30/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7957 - loss: 0.4330 - val_accuracy: 0.7809 - val_loss: 0.5471
Epoch 31/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7967 - loss: 0.4652 - val_accuracy: 0.7753 - val_loss: 0.5369
Epoch 32/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7843 - loss: 0.4738 - val_accuracy: 0.7809 - val_loss: 0.5663
Epoch 33/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8185 - loss: 0.4365 - val_accuracy: 0.7697 - val_loss: 0.5443
Epoch 34/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8188 - loss: 0.4349 - val_accuracy: 0.7753 - val_loss: 0.5603
Epoch 35/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8068 - loss: 0.4435 - val_accuracy: 0.7584 - val_loss: 0.5404
Epoch 36/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7825 - loss: 0.4845 - val_accuracy: 0.7697 - val_loss: 0.5399
Epoch 37/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4540 - val_accuracy: 0.7697 - val_loss: 0.5448
Epoch 38/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.4579 - val_accuracy: 0.7640 - val_loss: 0.5396
Epoch 39/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8181 - loss: 0.4242 - val_accuracy: 0.7697 - val_loss: 0.5467
Epoch 40/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.3982 - val_accuracy: 0.7697 - val_loss: 0.5386
Epoch 41/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8115 - loss: 0.4350 - val_accuracy: 0.7697 - val_loss: 0.5474
Epoch 42/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8122 - loss: 0.4223 - val_accuracy: 0.7753 - val_loss: 0.5650
Epoch 43/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8347 - loss: 0.3951 - val_accuracy: 0.7753 - val_loss: 0.5447
Epoch 44/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8165 - loss: 0.4386 - val_accuracy: 0.7753 - val_loss: 0.5438
Epoch 45/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4260 - val_accuracy: 0.7753 - val_loss: 0.5446
Epoch 46/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8222 - loss: 0.3889 - val_accuracy: 0.7697 - val_loss: 0.5496
Epoch 47/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8296 - loss: 0.4119 - val_accuracy: 0.7640 - val_loss: 0.5492
Epoch 48/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8128 - loss: 0.4252 - val_accuracy: 0.7753 - val_loss: 0.5575
Epoch 49/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8352 - loss: 0.3814 - val_accuracy: 0.7753 - val_loss: 0.5388
Epoch 50/50
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8123 - loss: 0.4171 - val_accuracy: 0.7753 - val_loss: 0.5518

### 13.4.3 Evaluating the models

#### Accuracy

In [110]:
print("Scores of the models")
print("Logistic regression:", lr_model.score(features_validation, labels_validation))
print("Decision tree:", dt_model.score(features_validation, labels_validation))
print("Naive Bayes:", nb_model.score(features_validation, labels_validation))
print("SVM:", svm_model.score(features_validation, labels_validation))
print("Random forest:", rf_model.score(features_validation, labels_validation))
print("Gradient boosting:", gb_model.score(features_validation, labels_validation))
print("AdaBoost:", ab_model.score(features_validation, labels_validation))
print("XGBoost:", xgboost_model.score(features_validation_xgboost, labels_validation))

loss, accuracy = model.evaluate(X_test, y_test)
print("Neural Network accuracy:", accuracy)

Scores of the models
Logistic regression: 0.7696629213483146
Decision tree: 0.7640449438202247
Naive Bayes: 0.7471910112359551
SVM: 0.6797752808988764
Random forest: 0.7752808988764045
Gradient boosting: 0.8089887640449438
AdaBoost: 0.7359550561797753
XGBoost: 0.7808988764044944
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - accuracy: 0.8024 - loss: 0.4608
Neural Network accuracy: 0.7932960987091064

#### Recall

In [111]:
from sklearn.metrics import recall_score

print("Recall of the models:")

lr_predicted_labels = lr_model.predict(features_validation)
print("Logistic regression:", recall_score(labels_validation, lr_predicted_labels))

dt_predicted_labels = dt_model.predict(features_validation)
print("Decision Tree:", recall_score(labels_validation, dt_predicted_labels))

nb_predicted_labels = nb_model.predict(features_validation)
print("Naive Bayes:", recall_score(labels_validation, nb_predicted_labels))

svm_predicted_labels = svm_model.predict(features_validation)
print("Support Vector Machine:", recall_score(labels_validation, svm_predicted_labels))

rf_predicted_labels = rf_model.predict(features_validation)
print("Random Forest:", recall_score(labels_validation, rf_predicted_labels))

gb_predicted_labels = gb_model.predict(features_validation)
print("Gradient boosting:", recall_score(labels_validation, gb_predicted_labels))

ab_predicted_labels = ab_model.predict(features_validation)
print("AdaBoost:", recall_score(labels_validation, ab_predicted_labels))

xgb_predicted_labels = xgboost_model.predict(features_validation_xgboost)
print("XGBoost:", recall_score(labels_validation, xgb_predicted_labels))

y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype(int)
print("Neural Network:", recall_score(y_test, y_pred))

Recall of the models:
Logistic regression: 0.6428571428571429
Decision Tree: 0.6285714285714286
Naive Bayes: 0.6857142857142857
Support Vector Machine: 0.2714285714285714
Random Forest: 0.6714285714285714
Gradient boosting: 0.6857142857142857
AdaBoost: 0.6142857142857143
XGBoost: 0.7142857142857143
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step
Neural Network: 0.6626506024096386

#### Precision

In [113]:
from sklearn.metrics import precision_score

print("Precision of the models:")

lr_predicted_labels = lr_model.predict(features_validation)
print("Logistic regression:", precision_score(labels_validation, lr_predicted_labels))

dt_predicted_labels = dt_model.predict(features_validation)
print("Decision Tree:", precision_score(labels_validation, dt_predicted_labels))

nb_predicted_labels = nb_model.predict(features_validation)
print("Naive Bayes:", precision_score(labels_validation, nb_predicted_labels))

svm_predicted_labels = svm_model.predict(features_validation)
print("Support Vector Machine:", precision_score(labels_validation, svm_predicted_labels))

rf_predicted_labels = rf_model.predict(features_validation)
print("Random Forest:", precision_score(labels_validation, rf_predicted_labels))

gb_predicted_labels = gb_model.predict(features_validation)
print("Gradient boosting:", precision_score(labels_validation, gb_predicted_labels))

ab_predicted_labels = ab_model.predict(features_validation)
print("AdaBoost:", precision_score(labels_validation, ab_predicted_labels))

xgb_predicted_labels = xgboost_model.predict(features_validation_xgboost)
print("XGBoost:", precision_score(labels_validation, xgb_predicted_labels))

y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype(int)
print("Neural Network:", precision_score(y_test, y_pred))

Precision of the models:
Logistic regression: 0.7377049180327869
Decision Tree: 0.7333333333333333
Naive Bayes: 0.676056338028169
Support Vector Machine: 0.76
Random Forest: 0.734375
Gradient boosting: 0.8
AdaBoost: 0.6825396825396826
XGBoost: 0.7246376811594203
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Neural Network: 0.859375

#### F1-score

In [114]:
from sklearn.metrics import f1_score

print("F1-scores of the models:")

lr_predicted_labels = lr_model.predict(features_validation)
print("Logistic regression:", f1_score(labels_validation, lr_predicted_labels))

dt_predicted_labels = dt_model.predict(features_validation)
print("Decision Tree:", f1_score(labels_validation, dt_predicted_labels))

nb_predicted_labels = nb_model.predict(features_validation)
print("Naive Bayes:", f1_score(labels_validation, nb_predicted_labels))

svm_predicted_labels = svm_model.predict(features_validation)
print("Support Vector Machine:", f1_score(labels_validation, svm_predicted_labels))

rf_predicted_labels = rf_model.predict(features_validation)
print("Random Forest:", f1_score(labels_validation, rf_predicted_labels))

gb_predicted_labels = gb_model.predict(features_validation)
print("Gradient boosting:", f1_score(labels_validation, gb_predicted_labels))

ab_predicted_labels = ab_model.predict(features_validation)
print("AdaBoost:", f1_score(labels_validation, ab_predicted_labels))

xgb_predicted_labels = xgboost_model.predict(features_validation_xgboost)
print("XGBoost:", f1_score(labels_validation, xgb_predicted_labels))

y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype(int)
print("Neural Network:", f1_score(y_test, y_pred))

F1-scores of the models:
Logistic regression: 0.6870229007633588
Decision Tree: 0.676923076923077
Naive Bayes: 0.6808510638297872
Support Vector Machine: 0.4
Random Forest: 0.7014925373134329
Gradient boosting: 0.7384615384615385
AdaBoost: 0.6466165413533834
XGBoost: 0.7194244604316546
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Neural Network: 0.7482993197278912

### 13.4.4 Testing the model

Finding the accuracy and the F1-score of the model in the testing set.

In [115]:
gb_model.score(features_test, labels_test)

0.8324022346368715

In [116]:
gb_predicted_test_labels = gb_model.predict(features_test)
f1_score(labels_test, gb_predicted_test_labels)

0.8026315789473685

## 13.5 Grid search

In [117]:
# Grid search with an rbf kernel

print("SVM grid search with a radial basis function kernel")

# rbf, C=1, gamma=0.1
svm_1_01 = SVC(kernel='rbf', C=1, gamma=0.1)
svm_1_01.fit(features_train, labels_train)
print("C=1, gamma=0.1", svm_1_01.score(features_validation, labels_validation))

# rbf, C=1, gamma=1
svm_1_1 = SVC(kernel='rbf', C=1, gamma=1)
svm_1_1.fit(features_train, labels_train)
print("C=1, gamma=1", svm_1_1.score(features_validation, labels_validation))

# rbf, C=1, gamma=10
svm_1_10 = SVC(kernel='rbf', C=1, gamma=10)
svm_1_10.fit(features_train, labels_train)
print("C=1, gamma=10", svm_1_10.score(features_validation, labels_validation))

# rbf, C=10, gamma=0.1
svm_10_01 = SVC(kernel='rbf', C=10, gamma=0.1)
svm_10_01.fit(features_train, labels_train)
print("C=10, gamma=0.1", svm_10_01.score(features_validation, labels_validation))

# rbf, C=10, gamma=1
svm_10_1 = SVC(kernel='rbf', C=10, gamma=1)
svm_10_1.fit(features_train, labels_train)
print("C=10, gamma=1", svm_10_1.score(features_validation, labels_validation))

# rbf, C=10, gamma=10
svm_10_10 = SVC(kernel='rbf', C=10, gamma=10)
svm_10_10.fit(features_train, labels_train)
print("C=10, gamma=10", svm_10_10.score(features_validation, labels_validation))

SVM grid search with a radial basis function kernel
C=1, gamma=0.1 0.702247191011236
C=1, gamma=1 0.6966292134831461
C=1, gamma=10 0.6685393258426966
C=10, gamma=0.1 0.7247191011235955
C=10, gamma=1 0.6910112359550562
C=10, gamma=10 0.651685393258427

In [118]:
from sklearn.model_selection import GridSearchCV

In [119]:
svm_parameters = {'kernel': ['rbf'],
                  'C': [0.01, 0.1, 1 , 10, 100],
                  'gamma': [0.01, 0.1, 1, 10, 100]
                }
svm = SVC()
svm_gs = GridSearchCV(estimator = svm,
                      param_grid = svm_parameters)
svm_gs.fit(features_train, labels_train)

svm_winner = svm_gs.best_estimator_
svm_winner

svm_winner.score(features_validation, labels_validation)

0.7191011235955056

In [120]:
svm_winner

SVC(C=10, gamma=0.01)

### 13.5.2 Grid search for XGboost model

In [121]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Prepare data
X_train = features_train.values
X_val   = features_validation.values
X_test  = features_test.values

y_train = labels_train.values
y_val   = labels_validation.values
y_test  = labels_test.values

# Base model
xgb = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=100
)

# Parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.3],
    'max_depth': [3, 4, 5, 6],
    'subsample': [0.7, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.9, 1.0]
}

# Grid search
grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=1,
    n_jobs=-1
)

grid.fit(X_train, y_train)

# Results
print("Best parameters found:", grid.best_params_)
print("Best cross-validation accuracy:", grid.best_score_)

# Test set evaluation
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print("\nTest accuracy:", acc)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 324 candidates, totalling 1620 fits
Best parameters found: {'colsample_bytree': 0.7, 'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 200, 'subsample': 1.0}
Best cross-validation accuracy: 0.8332569211779228

Test accuracy: 0.8379888268156425

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.95      0.86        96
           1       0.92      0.71      0.80        83

    accuracy                           0.84       179
   macro avg       0.86      0.83      0.83       179
weighted avg       0.85      0.84      0.83       179

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [18:57:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

## 13.6 Cross validation

In [125]:
# XGboost grid search params
grid.cv_results_

{'mean_fit_time': array([0.2322226 , 0.0354104 , 0.04047699, 0.07659836, 0.06765752,
        0.08407192, 0.24719605, 0.29496503, 0.12884827, 0.04748273,
        0.047824  , 0.03986154, 0.08425546, 0.08573794, 0.05787897,
        0.09749818, 0.126823  , 0.11251211, 0.05155454, 0.06956334,
        0.0561295 , 0.05935965, 0.06870604, 0.06428552, 0.10953455,
        0.09966578, 0.12967329, 0.05574718, 0.04064488, 0.0477984 ,
        0.05854378, 0.06281371, 0.0839191 , 0.08177977, 0.08194885,
        0.08662071, 0.01683006, 0.01785917, 0.0187304 , 0.03005352,
        0.02773967, 0.02954664, 0.05508757, 0.05194035, 0.04723353,
        0.0192585 , 0.02249241, 0.02081547, 0.03135786, 0.03324146,
        0.03068576, 0.05907693, 0.05929594, 0.06346574, 0.0258698 ,
        0.02199583, 0.02226357, 0.03610177, 0.03883672, 0.03618197,
        0.06530867, 0.07101383, 0.06915178, 0.02425394, 0.02716751,
        0.0242465 , 0.03992987, 0.04249597, 0.03998756, 0.07626152,
        0.07846727, 0.07827668, 0.0169879 , 0.01661663, 0.0181932 ,
        0.02688813, 0.02716742, 0.02733173, 0.05315299, 0.04954414,
        0.04663944, 0.0246088 , 0.02131515, 0.02346725, 0.0498939 ,
        0.04697762, 0.04354601, 0.07522783, 0.10257754, 0.0859303 ,
        0.02610269, 0.02917194, 0.03899736, 0.0525064 , 0.07122569,
        0.06260242, 0.11635256, 0.10449867, 0.08210473, 0.02722492,
        0.0364727 , 0.04136992, 0.06246037, 0.04742541, 0.04511304,
        0.07076087, 0.07101364, 0.06772504, 0.01870961, 0.01880317,
        0.02049146, 0.03810306, 0.0296906 , 0.03334846, 0.05484862,
        0.05386496, 0.05538311, 0.02216573, 0.02420192, 0.02460241,
        0.03669753, 0.03776689, 0.04162145, 0.06477909, 0.06397405,
        0.06608   , 0.02491651, 0.02336407, 0.02421961, 0.04469309,
        0.04405088, 0.04433107, 0.07798524, 0.07690659, 0.07698569,
        0.02788782, 0.02676048, 0.02549844, 0.04806147, 0.05066085,
        0.04584055, 0.08462472, 0.08850803, 0.09252787, 0.0178196 ,
        0.01754179, 0.02152491, 0.03023534, 0.02854958, 0.02884393,
        0.05196781, 0.0498313 , 0.04821796, 0.02279   , 0.0204731 ,
        0.01987686, 0.03488445, 0.03397326, 0.04179482, 0.05977235,
        0.0603765 , 0.06455822, 0.02346206, 0.02450328, 0.02355857,
        0.03809495, 0.04712224, 0.04016304, 0.07049494, 0.07108645,
        0.06861959, 0.02546153, 0.02777605, 0.02716427, 0.04243307,
        0.04954929, 0.0470551 , 0.07510943, 0.07845445, 0.07888541,
        0.01750388, 0.01733913, 0.01854563, 0.03256559, 0.03011489,
        0.03012147, 0.05039749, 0.05063534, 0.05466256, 0.02567701,
        0.02850833, 0.03010983, 0.04129338, 0.060218  , 0.04627285,
        0.08143277, 0.11482277, 0.07035975, 0.04839191, 0.04063797,
        0.03191509, 0.05991454, 0.06487293, 0.05379233, 0.09558558,
        0.11624756, 0.09212151, 0.03319397, 0.02753458, 0.03616309,
        0.04943566, 0.05118961, 0.04287934, 0.07235446, 0.07734199,
        0.07219033, 0.01854229, 0.0179224 , 0.01910982, 0.03018255,
        0.03031807, 0.02987881, 0.05980735, 0.05724125, 0.05399652,
        0.02292686, 0.02155108, 0.02030606, 0.03873258, 0.035286  ,
        0.03620729, 0.06934123, 0.0705668 , 0.07013888, 0.02352276,
        0.0252954 , 0.02385631, 0.04264483, 0.04573107, 0.04203696,
        0.0817019 , 0.08432379, 0.08063688, 0.02574511, 0.0282918 ,
        0.02736621, 0.046804  , 0.05035396, 0.05068898, 0.09280248,
        0.09423776, 0.09037843, 0.01942859, 0.01825624, 0.01894937,
        0.02887712, 0.04376769, 0.03914938, 0.05136137, 0.05233102,
        0.05252032, 0.02041273, 0.02208977, 0.02202072, 0.03452406,
        0.03507667, 0.03608227, 0.06659832, 0.0605803 , 0.06625705,
        0.0248178 , 0.0249526 , 0.02449479, 0.04112725, 0.03897185,
        0.04153762, 0.07803836, 0.06994281, 0.07143655, 0.0273201 ,
        0.02596645, 0.02711887, 0.04690609, 0.04592199, 0.05298185,
        0.07838583, 0.08139567, 0.08208075, 0.01670423, 0.01783242,
        0.01670523, 0.03113852, 0.02811985, 0.03055735, 0.06137662,
        0.07087955, 0.06353693, 0.0307425 , 0.0264956 , 0.04032269,
        0.05925074, 0.06015978, 0.06671286, 0.10209413, 0.09762778,
        0.09790025, 0.03771534, 0.04029551, 0.03086505, 0.04597354,
        0.05664363, 0.06426396, 0.08601856, 0.08562274, 0.06729088,
        0.02321291, 0.02407846, 0.02441463, 0.04374824, 0.0409709 ,
        0.04176931, 0.07293792, 0.08277688, 0.06955943]),
 'std_fit_time': array([2.58683091e-01, 1.12441311e-02, 3.62981916e-03, 1.32168821e-02,
        3.39849748e-02, 1.04869336e-02, 7.83777686e-02, 3.00048348e-02,
        5.17080253e-02, 3.86881095e-03, 5.41936933e-03, 1.93359051e-02,
        1.73282664e-02, 2.64908696e-02, 1.59624474e-02, 2.28194392e-02,
        1.23237779e-02, 2.48377702e-02, 8.05773824e-03, 1.25646130e-02,
        1.77556762e-02, 1.72415558e-02, 2.10420563e-02, 1.77921708e-02,
        3.03078168e-02, 2.38250811e-02, 3.40727283e-02, 2.28305812e-02,
        1.23957071e-02, 1.26877038e-02, 1.83883697e-02, 2.00715544e-02,
        1.66177307e-02, 6.80766614e-03, 3.37375328e-03, 4.57727242e-03,
        2.47286003e-04, 1.97612526e-03, 1.82394577e-03, 3.35252846e-03,
        1.95161371e-03, 5.02385796e-03, 6.08152431e-03, 7.12699784e-03,
        1.13180735e-03, 2.94581491e-04, 4.44071034e-03, 1.97076554e-03,
        8.91647830e-04, 2.84919971e-03, 3.68206991e-04, 3.86001612e-03,
        5.20491209e-03, 7.84467557e-03, 6.67999644e-03, 1.10837044e-03,
        1.52199549e-03, 6.11140654e-04, 5.42482028e-03, 1.69810632e-03,
        1.94828358e-03, 4.61449005e-03, 7.49566871e-03, 7.70798359e-04,
        3.16508491e-03, 5.22416127e-04, 1.60808415e-03, 4.15271955e-03,
        4.08329137e-04, 6.81275479e-03, 4.76323293e-03, 1.25791434e-02,
        8.63182717e-04, 5.21932553e-04, 2.80895133e-03, 6.51845482e-04,
        1.10346267e-03, 2.07322862e-03, 6.35059726e-03, 1.84757841e-03,
        5.77665989e-04, 4.78869816e-03, 2.54336402e-03, 5.61592822e-03,
        8.49245079e-03, 1.26291729e-02, 8.58917047e-03, 3.36523040e-02,
        2.97399977e-02, 1.67870611e-02, 7.43465355e-03, 8.69691139e-03,
        6.35488207e-03, 1.29915156e-02, 9.25925698e-03, 1.22030207e-03,
        1.82139066e-02, 2.77775058e-02, 1.85096438e-02, 5.60520199e-03,
        4.82465447e-03, 8.59096212e-03, 1.22594911e-02, 1.04339688e-02,
        7.99029878e-03, 4.54211185e-03, 2.43139221e-03, 9.66159168e-04,
        1.36181965e-03, 6.49178433e-04, 4.53834609e-03, 1.11565981e-02,
        1.53432061e-04, 4.49448437e-03, 3.03158206e-03, 1.42226715e-03,
        4.41718427e-03, 3.86499068e-03, 2.44074414e-03, 6.05367750e-03,
        2.30777101e-03, 4.65840944e-03, 9.60190121e-03, 2.89142596e-03,
        1.43211156e-03, 4.48799738e-03, 4.30091260e-03, 1.04282813e-03,
        1.79858812e-03, 7.67115842e-03, 4.65530347e-03, 3.45226260e-03,
        5.50217452e-03, 2.12165792e-03, 1.75695969e-03, 3.48536025e-03,
        1.40608747e-03, 8.31837979e-04, 4.00079353e-03, 7.11334418e-03,
        7.96542099e-04, 1.77661185e-03, 5.67882678e-03, 1.07612095e-02,
        1.54744494e-03, 4.13613141e-04, 5.52925352e-03, 2.87537508e-03,
        5.91874679e-04, 1.43646440e-03, 5.09741641e-03, 8.19929024e-04,
        1.42093978e-03, 3.48017763e-03, 5.87685782e-04, 1.97785282e-04,
        1.85743063e-03, 1.20437992e-03, 1.31415152e-02, 1.97489059e-03,
        1.14454208e-03, 8.78506750e-03, 8.74723488e-04, 2.94085875e-03,
        1.15690433e-03, 8.70083776e-04, 7.49825361e-03, 2.01368270e-03,
        1.48997389e-03, 4.08747643e-03, 1.50912047e-03, 1.63602384e-03,
        4.59657086e-03, 2.20178173e-03, 7.25462980e-04, 1.12606993e-02,
        4.87884318e-03, 9.04166134e-04, 2.62560291e-03, 5.50536303e-03,
        1.25547151e-03, 7.50850532e-04, 2.14375199e-03, 6.34675749e-03,
        3.01438792e-03, 3.99732095e-03, 1.66201868e-03, 1.54076470e-03,
        4.16807740e-03, 6.32937269e-03, 7.99150709e-03, 5.42150128e-03,
        1.07388247e-02, 9.78317985e-03, 1.27441914e-02, 2.31642236e-02,
        1.24515390e-02, 1.72298830e-02, 7.90176103e-03, 1.12005167e-02,
        9.75949537e-03, 2.15081347e-02, 1.14828223e-02, 1.11415863e-02,
        9.54433959e-03, 1.39170220e-02, 1.79070442e-02, 9.27294934e-03,
        2.29623321e-03, 6.03111094e-03, 1.10275049e-02, 1.60718169e-02,
        5.04365914e-03, 6.03979720e-03, 8.96916656e-03, 4.04200818e-03,
        1.17473358e-03, 6.45138912e-04, 2.76563215e-03, 1.68625011e-03,
        8.38344811e-04, 1.25016183e-03, 7.54578260e-03, 5.54146028e-03,
        1.34013130e-03, 3.32792900e-03, 1.18152895e-03, 6.17673556e-04,
        4.50964929e-03, 2.08588566e-04, 1.24560403e-03, 4.22412170e-03,
        8.82426444e-03, 5.85601107e-03, 1.49014393e-03, 1.85908534e-03,
        1.33539820e-03, 4.56322317e-03, 8.42135268e-03, 9.56542356e-04,
        3.76653764e-03, 8.31307978e-03, 1.65635932e-03, 5.86123793e-04,
        3.49902438e-03, 1.30020921e-03, 7.90416561e-04, 3.50058622e-03,
        4.97035368e-03, 8.36875097e-03, 4.66702297e-03, 2.67706412e-03,
        3.92816785e-03, 9.62943207e-04, 3.46594060e-03, 4.72236989e-04,
        1.32991146e-02, 1.08625047e-02, 6.94456270e-04, 1.24061035e-03,
        4.01538597e-03, 1.45582724e-03, 2.82244396e-03, 1.74089698e-03,
        7.36094582e-04, 1.99643136e-03, 1.42369210e-03, 8.66260997e-03,
        1.09178172e-03, 7.69782397e-03, 1.75070945e-03, 1.26721042e-03,
        5.34513496e-04, 3.45037808e-03, 7.12481577e-04, 2.83442298e-03,
        5.40821555e-03, 1.19987174e-03, 3.71238040e-03, 3.88210484e-03,
        3.23142181e-04, 1.35696423e-03, 3.70329005e-03, 1.75404232e-03,
        6.41627440e-03, 4.30140566e-03, 4.01225077e-03, 4.38266905e-03,
        2.63313719e-04, 1.50770691e-03, 4.65843679e-04, 5.90674611e-03,
        5.56216379e-04, 4.78929027e-03, 3.82443618e-03, 2.20620429e-02,
        1.41482699e-02, 5.87745150e-03, 8.78962780e-03, 5.04571411e-03,
        1.09995541e-02, 8.46229208e-03, 9.92528556e-03, 2.43479436e-02,
        1.55123292e-02, 7.45548205e-03, 6.54426567e-03, 4.70505196e-03,
        9.51683086e-03, 9.82287921e-03, 1.01408683e-02, 1.14819464e-02,
        1.49417288e-02, 9.42668491e-03, 2.26738116e-03, 1.73015091e-04,
        2.70158344e-04, 3.07176506e-04, 3.21483459e-03, 4.48125249e-04,
        1.36424367e-03, 2.39264140e-03, 7.98202237e-03, 6.47097383e-03]),
 'mean_score_time': array([0.00595565, 0.00552254, 0.00756693, 0.00836115, 0.00598445,
        0.00748777, 0.01701894, 0.01773777, 0.00733109, 0.0056829 ,
        0.00368934, 0.00352693, 0.00717258, 0.00835166, 0.00532217,
        0.00523682, 0.00493722, 0.00616908, 0.00639858, 0.00730829,
        0.00415893, 0.0054493 , 0.00314488, 0.00410962, 0.00487356,
        0.00333424, 0.00575824, 0.00597267, 0.00403085, 0.00471988,
        0.00324306, 0.00431542, 0.00414319, 0.0038372 , 0.00298567,
        0.00302944, 0.00216017, 0.00214996, 0.00208364, 0.00221181,
        0.00237412, 0.00221319, 0.00280585, 0.00286174, 0.00248899,
        0.00244069, 0.00222068, 0.00216117, 0.00225101, 0.00231795,
        0.00225148, 0.00266833, 0.00264874, 0.00274153, 0.00220809,
        0.00213008, 0.00221601, 0.00249534, 0.00245595, 0.00246253,
        0.00269055, 0.00300646, 0.0045085 , 0.00236311, 0.00277033,
        0.00238609, 0.00248609, 0.00298123, 0.00245771, 0.00300412,
        0.00297966, 0.00317178, 0.00241122, 0.00242176, 0.00207443,
        0.00218811, 0.00219579, 0.0022553 , 0.00292997, 0.00269465,
        0.00295501, 0.00299959, 0.00309258, 0.00240717, 0.00439153,
        0.00340643, 0.00362682, 0.00277224, 0.00571246, 0.00484934,
        0.00266237, 0.00308189, 0.00540156, 0.0046793 , 0.00441084,
        0.00373578, 0.00521808, 0.00366631, 0.00442266, 0.00309806,
        0.00293083, 0.00382385, 0.00458503, 0.00365062, 0.00259042,
        0.00302229, 0.00292907, 0.00295639, 0.00212111, 0.00214047,
        0.00234723, 0.00244613, 0.00226269, 0.00233088, 0.002701  ,
        0.00246496, 0.00246973, 0.00218053, 0.00242743, 0.00228157,
        0.00229926, 0.00264435, 0.00230718, 0.00261464, 0.00257792,
        0.0026557 , 0.00219946, 0.0021843 , 0.00215168, 0.00242672,
        0.00235929, 0.00407805, 0.00301986, 0.00287156, 0.00280724,
        0.00218096, 0.00218415, 0.002139  , 0.00323043, 0.00364299,
        0.00246997, 0.00294776, 0.00297832, 0.00296931, 0.00206881,
        0.00247998, 0.00215931, 0.00258141, 0.00217719, 0.00224309,
        0.00246954, 0.00241904, 0.0024744 , 0.00256858, 0.00213122,
        0.00218306, 0.00230532, 0.00253148, 0.00232182, 0.00262237,
        0.00265532, 0.00264335, 0.00257277, 0.0021956 , 0.00214534,
        0.0025785 , 0.00317712, 0.00243115, 0.00288939, 0.00304222,
        0.00284362, 0.00266318, 0.00225034, 0.00231414, 0.00255504,
        0.00309644, 0.00261245, 0.0031188 , 0.0030304 , 0.00301838,
        0.00209222, 0.00206852, 0.0025444 , 0.00298147, 0.0031498 ,
        0.00222578, 0.00246482, 0.00255966, 0.00277181, 0.00234346,
        0.00303545, 0.00356832, 0.00301132, 0.00457997, 0.00297465,
        0.00389061, 0.00650883, 0.00293951, 0.00560098, 0.00375309,
        0.00377007, 0.00398335, 0.00323687, 0.00388255, 0.00526352,
        0.00691466, 0.00525894, 0.00341706, 0.00250778, 0.00390463,
        0.00262938, 0.00307012, 0.00246744, 0.00313482, 0.00300784,
        0.00287604, 0.00216947, 0.00203619, 0.00207973, 0.00216088,
        0.00228758, 0.00216837, 0.00249314, 0.00289097, 0.00247092,
        0.00215816, 0.00208635, 0.00217896, 0.00253644, 0.0025948 ,
        0.00229311, 0.00364265, 0.003022  , 0.0025692 , 0.00219526,
        0.00221128, 0.00221372, 0.00253677, 0.00280342, 0.0023921 ,
        0.0027976 , 0.00280299, 0.00288491, 0.00223145, 0.00224986,
        0.00221009, 0.0024775 , 0.00244622, 0.00262332, 0.00306501,
        0.00303507, 0.00309262, 0.00216813, 0.00231867, 0.00209756,
        0.00222168, 0.00433483, 0.00263062, 0.00252867, 0.00250664,
        0.0025219 , 0.00227742, 0.00212421, 0.00215592, 0.00231414,
        0.00323324, 0.0026875 , 0.00319457, 0.0027338 , 0.0031723 ,
        0.00222859, 0.00215454, 0.00227389, 0.00234709, 0.00236788,
        0.0029048 , 0.00299435, 0.0028677 , 0.00278087, 0.0021893 ,
        0.00227938, 0.00240636, 0.00264654, 0.00262127, 0.00295463,
        0.0030447 , 0.00300589, 0.00310593, 0.00211096, 0.00206437,
        0.00206718, 0.00219812, 0.00215564, 0.00216012, 0.00465512,
        0.00355744, 0.00355411, 0.00423288, 0.00470366, 0.00375957,
        0.00423822, 0.00440888, 0.00416446, 0.00529985, 0.00413198,
        0.00504503, 0.00393353, 0.00387163, 0.00260816, 0.00544624,
        0.00510001, 0.00399938, 0.00352545, 0.00360289, 0.0029418 ,
        0.00226483, 0.0022893 , 0.00220823, 0.00240355, 0.00239625,
        0.00243611, 0.00288973, 0.00332904, 0.00273709]),
 'std_score_time': array([3.63202823e-03, 2.35041886e-03, 3.16601791e-03, 3.86806285e-03,
        3.86077617e-03, 3.30135798e-03, 8.34102137e-03, 8.25738140e-03,
        2.88338153e-03, 3.35135150e-03, 8.43452237e-04, 1.12969460e-03,
        2.83185969e-03, 7.03065186e-03, 2.99361786e-03, 2.00795084e-03,
        1.37205475e-03, 1.95471594e-03, 2.15331603e-03, 1.62118573e-03,
        1.62445231e-03, 3.06843034e-03, 8.85811863e-04, 1.65656684e-03,
        1.72504349e-03, 2.24539646e-04, 1.70189021e-03, 3.03512374e-03,
        1.63940588e-03, 1.91440303e-03, 1.33881808e-03, 1.61962127e-03,
        1.39710777e-03, 1.64032977e-03, 6.41211067e-05, 1.19843949e-04,
        9.56127588e-05, 7.79380963e-05, 6.03295307e-05, 5.77949454e-05,
        1.90388926e-04, 1.01686281e-04, 5.77054384e-04, 6.02412729e-04,
        1.04838329e-04, 5.22196540e-04, 8.26304451e-05, 5.72066688e-05,
        7.02534398e-05, 5.01732399e-05, 9.37814685e-05, 1.36580963e-04,
        7.72958181e-05, 2.57869082e-04, 6.78776648e-05, 3.64752064e-05,
        1.11000951e-04, 2.08781253e-04, 6.29560499e-05, 7.95145942e-05,
        6.32011633e-05, 2.34157100e-04, 3.27362894e-03, 1.68980661e-04,
        9.34674233e-04, 1.01587020e-04, 7.95168818e-05, 9.45379512e-04,
        4.38056364e-05, 3.93491501e-05, 4.82316955e-05, 6.19858312e-04,
        6.92384246e-04, 8.06265021e-04, 7.52465655e-05, 5.20018413e-05,
        2.91383791e-05, 1.63008971e-04, 4.13793049e-04, 1.98045426e-04,
        6.92478107e-04, 1.60902635e-03, 1.08763691e-03, 3.72355649e-04,
        1.35574508e-03, 8.14851066e-04, 1.60111281e-03, 1.64644117e-04,
        1.86081190e-03, 2.69033746e-03, 8.23671169e-04, 8.76323976e-04,
        2.80307080e-03, 1.53773833e-03, 6.01214938e-04, 1.42595729e-03,
        5.30455211e-04, 1.02870415e-03, 1.18477006e-03, 9.92981106e-04,
        7.57066600e-04, 1.41910724e-03, 1.26039256e-03, 1.70437007e-03,
        1.87196515e-04, 1.18741989e-04, 4.56187894e-05, 8.66051017e-05,
        6.64728102e-05, 3.62823887e-05, 8.14067312e-05, 4.18416969e-04,
        4.27815152e-05, 7.68939801e-05, 1.03748129e-04, 6.18524886e-05,
        6.32571534e-05, 7.17793413e-05, 2.53232794e-04, 2.16213479e-04,
        2.78708770e-05, 6.99820100e-04, 7.34649625e-05, 5.05099987e-05,
        4.85956724e-05, 1.93163396e-04, 2.44726655e-05, 3.58350659e-05,
        3.95649580e-05, 1.07070341e-04, 6.09670572e-05, 2.84454840e-03,
        1.92277003e-04, 5.36416159e-05, 4.96132049e-05, 3.19955957e-05,
        3.05678282e-05, 3.05937026e-05, 1.14531249e-03, 2.25717456e-03,
        6.53890326e-05, 3.30896816e-05, 5.43031485e-05, 6.87101332e-05,
        4.48194969e-05, 6.25437609e-04, 1.09687410e-04, 8.21808132e-04,
        2.83043725e-05, 7.27217157e-05, 1.14931901e-04, 7.93872149e-05,
        1.94730312e-04, 8.23081126e-04, 2.76495662e-05, 1.11697066e-04,
        6.15850281e-05, 1.51383550e-04, 5.80357250e-05, 6.38976026e-05,
        2.10021734e-05, 6.18728139e-05, 6.81305309e-04, 2.32953375e-05,
        4.68229810e-05, 1.06379260e-04, 1.65929799e-03, 1.18481992e-04,
        1.13323037e-04, 1.41203954e-04, 5.57730315e-05, 8.45392751e-04,
        9.97078470e-05, 1.25818018e-04, 2.43145229e-04, 1.15322679e-03,
        6.78990999e-05, 8.49778669e-05, 1.09566928e-04, 2.87331128e-04,
        1.21250660e-04, 3.09246452e-05, 7.89341504e-04, 1.66080246e-03,
        1.66353206e-03, 8.28131207e-05, 2.99628322e-05, 2.55583249e-04,
        7.37917481e-05, 5.91034608e-05, 8.00087945e-04, 1.13067461e-03,
        8.69233473e-04, 1.17832659e-03, 9.08942791e-04, 1.66081897e-03,
        1.34960211e-03, 7.96823404e-04, 1.05881109e-03, 1.59407791e-03,
        1.89492138e-03, 1.96441088e-03, 6.08505620e-04, 1.49243792e-03,
        7.66043657e-04, 2.67000999e-03, 1.73702890e-03, 8.67941144e-04,
        3.37883311e-04, 8.37171463e-04, 2.56830248e-04, 7.95412891e-04,
        4.14835721e-05, 5.01819325e-04, 1.21200844e-04, 3.62499749e-05,
        1.45808086e-04, 2.47476188e-05, 5.77687774e-05, 1.64122058e-05,
        2.55826553e-04, 6.17866520e-05, 8.91110291e-05, 8.26983683e-04,
        3.71141692e-05, 1.01649895e-04, 3.35113067e-05, 1.23590488e-04,
        3.03720439e-04, 3.97028363e-04, 2.82877390e-05, 1.95174449e-03,
        8.53435273e-04, 5.74680772e-05, 3.76180699e-05, 4.74455129e-05,
        1.00154988e-04, 3.72211126e-04, 7.26889516e-04, 5.04986985e-05,
        1.20599084e-04, 9.16795052e-05, 2.32351714e-04, 2.94222824e-05,
        6.28741211e-05, 4.06046930e-05, 6.31390019e-05, 4.33807568e-05,
        2.28958266e-04, 7.85813459e-05, 4.04561976e-05, 1.00062957e-04,
        7.90281026e-05, 1.21930385e-04, 1.92251139e-05, 6.22345748e-05,
        2.66802674e-03, 4.64499962e-04, 7.99129856e-05, 6.00107852e-05,
        9.51531626e-05, 2.27094336e-04, 3.10334913e-05, 3.97513489e-05,
        5.99881992e-05, 1.61521926e-03, 5.87383902e-04, 8.79100831e-04,
        1.58878935e-04, 7.96829085e-04, 5.17252061e-05, 3.03758369e-05,
        2.46173878e-04, 8.77637670e-05, 3.80833214e-05, 1.16203531e-03,
        2.17642729e-04, 1.10153202e-04, 6.71875908e-05, 8.41104254e-05,
        1.05304021e-04, 2.70614771e-04, 1.52280662e-04, 1.43687945e-04,
        7.54033163e-04, 1.58021676e-04, 3.78581678e-05, 1.08525602e-04,
        7.76212686e-05, 7.47495441e-05, 5.93164342e-05, 6.97159082e-05,

In [122]:
svm_gs.cv_results_

{'mean_fit_time': array([0.00728006, 0.00750895, 0.00864244, 0.00890589, 0.00833611,
        0.00760994, 0.00778251, 0.00867577, 0.0091938 , 0.00857806,
        0.00730915, 0.00829787, 0.00881834, 0.01006265, 0.00987768,
        0.00939074, 0.00930252, 0.01095066, 0.01055713, 0.00933113,
        0.01131492, 0.01372323, 0.01002059, 0.01038547, 0.00955777]),
 'std_fit_time': array([5.59697136e-04, 4.83698123e-05, 6.49428210e-04, 1.83383041e-04,
        1.65968542e-04, 1.07290257e-03, 1.26527767e-04, 1.86257282e-04,
        1.76084451e-04, 1.25651070e-04, 2.32213890e-04, 3.08579942e-04,
        1.66739898e-04, 1.50506893e-03, 2.24360100e-03, 1.26994830e-03,
        6.49550801e-04, 1.18172477e-03, 4.06506499e-04, 7.63223416e-05,
        1.24590563e-03, 1.58387534e-03, 5.07380003e-04, 4.61600472e-04,
        3.30688938e-04]),
 'mean_score_time': array([0.00326509, 0.00333018, 0.00361643, 0.00375609, 0.00378284,
        0.00323462, 0.00336618, 0.00362186, 0.00375748, 0.00370498,
        0.00305672, 0.00383067, 0.00350499, 0.0042098 , 0.00365305,
        0.00302258, 0.00301094, 0.00351462, 0.00365028, 0.00361652,
        0.00270786, 0.00290732, 0.0035121 , 0.00361819, 0.00360174]),
 'std_score_time': array([6.11388919e-05, 3.43932828e-05, 6.63526402e-05, 2.22583377e-05,
        1.09277990e-04, 3.39617203e-05, 4.13089069e-05, 4.11589196e-05,
        8.93645504e-05, 5.19501774e-05, 3.61709823e-05, 1.14879157e-03,
        4.45979143e-05, 1.04439563e-03, 6.67774647e-05, 2.72798809e-04,
        2.29682119e-05, 6.85090052e-05, 5.70353056e-05, 2.62366187e-05,
        9.85243655e-05, 3.88431795e-05, 2.03977337e-04, 5.57092752e-05,
        4.68800046e-05]),
 'param_C': masked_array(data=[0.01, 0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1, 0.1,
                    1.0, 1.0, 1.0, 1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    100.0, 100.0, 100.0, 100.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_gamma': masked_array(data=[0.01, 0.1, 1.0, 10.0, 100.0, 0.01, 0.1, 1.0, 10.0,
                    100.0, 0.01, 0.1, 1.0, 10.0, 100.0, 0.01, 0.1, 1.0,
                    10.0, 100.0, 0.01, 0.1, 1.0, 10.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.01, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 0.01, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 0.1, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 1, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 10, 'gamma': 100, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 0.01, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 0.1, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 1, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 10, 'kernel': 'rbf'},
  {'C': 100, 'gamma': 100, 'kernel': 'rbf'}],
 'split0_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.65420561, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.71962617, 0.73831776, 0.6728972 , 0.70093458, 0.70093458,
        0.82242991, 0.71962617, 0.6728972 , 0.70093458, 0.70093458,
        0.80373832, 0.74766355, 0.6635514 , 0.70093458, 0.70093458]),
 'split1_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.65420561, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.64485981, 0.71028037, 0.68224299, 0.6635514 , 0.6635514 ,
        0.73831776, 0.73831776, 0.6728972 , 0.65420561, 0.6635514 ,
        0.76635514, 0.74766355, 0.64485981, 0.65420561, 0.6635514 ]),
 'split2_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.6728972 , 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.71962617, 0.79439252, 0.73831776, 0.70093458, 0.71028037,
        0.81308411, 0.79439252, 0.75700935, 0.70093458, 0.71028037,
        0.82242991, 0.74766355, 0.73831776, 0.71028037, 0.71028037]),
 'split3_test_score': array([0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.64485981, 0.64485981, 0.64485981, 0.64485981, 0.64485981,
        0.70093458, 0.77570093, 0.74766355, 0.70093458, 0.70093458,
        0.81308411, 0.75700935, 0.73831776, 0.70093458, 0.70093458,
        0.80373832, 0.74766355, 0.74766355, 0.70093458, 0.70093458]),
 'split4_test_score': array([0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 ,
        0.66037736, 0.6509434 , 0.6509434 , 0.6509434 , 0.6509434 ,
        0.70754717, 0.80188679, 0.77358491, 0.69811321, 0.70754717,
        0.8490566 , 0.76415094, 0.77358491, 0.70754717, 0.69811321,
        0.82075472, 0.75471698, 0.77358491, 0.70754717, 0.69811321]),
 'mean_test_score': array([0.64607653, 0.64607653, 0.64607653, 0.64607653, 0.64607653,
        0.65730912, 0.64607653, 0.64607653, 0.64607653, 0.64607653,
        0.69851878, 0.76411568, 0.72294128, 0.69289367, 0.69664962,
        0.8071945 , 0.75469935, 0.72294128, 0.6929113 , 0.69476283,
        0.80340328, 0.74907424, 0.71359549, 0.69478046, 0.69476283]),
 'std_test_score': array([0.00243343, 0.00243343, 0.00243343, 0.00243343, 0.00243343,
        0.00923744, 0.00243343, 0.00243343, 0.00243343, 0.00243343,
        0.02777652, 0.03476014, 0.03891829, 0.01471177, 0.01695151,
        0.03687258, 0.0251742 , 0.04235721, 0.01952157, 0.0161391 ,
        0.02017857, 0.00282137, 0.05019872, 0.02061699, 0.0161391 ]),
 'rank_test_score': array([17, 17, 17, 17, 17, 16, 17, 17, 17, 17,  9,  3,  6, 15, 10,  1,  4,
         6, 14, 12,  2,  5,  8, 11, 12], dtype=int32)}

## Exercise 13.1

### Loading and exploring the test dataset

In [139]:
# IMPORTANT: ONLY RUN THIS CELL IF YOU ARE WORKING ON A COLAB

url = "https://raw.githubusercontent.com/luisguiserrano/manning/master/Chapter_13_End_to_end_example/test.csv"
test_data = pd.read_csv(url)
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

### Cleaning up the test data

In [140]:
test_data.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

#### Droping column that is missing too many values

In [141]:
# Cleaning the data
processed_test_data = test_data.drop('Cabin', axis=1)

#### Filling in missing data

Filling in missing ages with median age of Passengers

In [142]:
median_age = test_data["Age"].median()
median_age

processed_test_data["Age"] = processed_test_data["Age"].fillna(median_age)
median_age

27.0

In [143]:
processed_test_data.isna().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

Filling in missing Fares with mean (Average) fare of Passengers

In [144]:
average_fare = float(test_data["Fare"].mean())
processed_test_data["Fare"] = processed_test_data["Fare"].fillna(average_fare)
average_fare

35.627188489208635

In [146]:
processed_test_data.isna().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [148]:
processed_test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [149]:
processed_test_data.to_csv('./cleaned_titanic_test_data.csv', index=None)

### Manipulating the features

In [185]:
processed_test_data = pd.read_csv('./cleaned_titanic_test_data.csv')
processed_test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [186]:
gender_columns = pd.get_dummies(processed_test_data['Sex'], prefix='Sex')
embarked_columns = pd.get_dummies(processed_test_data["Embarked"], prefix="Embarked")

processed_test_data = pd.concat([processed_test_data, gender_columns], axis=1)
processed_test_data = pd.concat([processed_test_data, embarked_columns], axis=1)
processed_test_data = processed_test_data.assign(Embarked_U=False)

processed_test_data = processed_test_data.drop(['Sex', 'Embarked'], axis=1)

In [187]:
class_survived = processed_test_data[['Pclass']]

first_class = class_survived[class_survived['Pclass'] == 1]
second_class = class_survived[class_survived['Pclass'] == 2]
third_class = class_survived[class_survived['Pclass'] == 3]

In [188]:
categorized_pclass_columns = pd.get_dummies(processed_test_data['Pclass'], prefix='Pclass')
processed_test_data = pd.concat([processed_test_data, categorized_pclass_columns], axis=1)
processed_test_data = processed_test_data.drop(['Pclass'], axis=1)

In [190]:
processed_test_data.head()

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3
0,892,"Kelly, Mr. James",34.5,0,0,330911,7.8292,False,True,False,True,False,False,False,False,True
1,893,"Wilkes, Mrs. James (Ellen Needs)",47.0,1,0,363272,7.0000,True,False,False,False,True,False,False,False,True
2,894,"Myles, Mr. Thomas Francis",62.0,0,0,240276,9.6875,False,True,False,True,False,False,False,True,False
3,895,"Wirz, Mr. Albert",27.0,0,0,315154,8.6625,False,True,False,False,True,False,False,False,True
4,896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.0,1,1,3101298,12.2875,True,False,False,False,True,False,False,False,True

#### Binning

In [191]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80]
categorized_age_test = pd.cut(processed_test_data['Age'], bins)
processed_test_data['Categorized_age'] = categorized_age_test
processed_test_data = processed_test_data.drop(["Age"], axis=1)

In [192]:
cagegorized_age_columns_test = pd.get_dummies(processed_test_data['Categorized_age'], prefix='Categorized_age')
processed_test_data = pd.concat([processed_test_data, cagegorized_age_columns_test], axis=1)
processed_test_data = processed_test_data.drop(['Categorized_age'], axis=1)

#### Feature selection

In [193]:
processed_test_data = processed_test_data.drop(['Name', 'Ticket', 'PassengerId'], axis=1)

In [194]:
processed_test_data.head()

,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3,"Categorized_age_(0, 10]","Categorized_age_(10, 20]","Categorized_age_(20, 30]","Categorized_age_(30, 40]","Categorized_age_(40, 50]","Categorized_age_(50, 60]","Categorized_age_(60, 70]","Categorized_age_(70, 80]"
0,0,0,7.8292,False,True,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False
1,1,0,7.0000,True,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False
2,0,0,9.6875,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False
3,0,0,8.6625,False,True,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False
4,1,1,12.2875,True,False,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False

In [195]:
processed_test_data.to_csv('./preprocessed_titanic_test_data.csv', index=None)

### Testing the model

In [196]:
# XGboost grid searched (hyperparam tuned) model
best_model.predict(processed_test_data)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [206]:
print("From", len(processed_test_data), "Passengers", best_model.predict(processed_test_data).sum(), "survived according to XGboost (best) model")

From 418 Passengers 125 survived according to XGboost (best) model

In [205]:
lr_model.predict(processed_test_data)

print("What other models think, how many passengers survived Titanic from test set:")
print("Logistic regression: Total:", len(processed_test_data), "Survived:", lr_model.predict(processed_test_data).sum())
print("Decision tree: Total:", len(processed_test_data), "Survived:", dt_model.predict(processed_test_data).sum())
print("Naive Bayes: Total:", len(processed_test_data), "Survived:", nb_model.predict(processed_test_data).sum())
print("SVM: Total:", len(processed_test_data), "Survived:", svm_model.predict(processed_test_data).sum())
print("SVM (winner): Total:", len(processed_test_data), "Survived:", svm_winner.predict(processed_test_data).sum())
print("Random forest: Total:", len(processed_test_data), "Survived:", rf_model.predict(processed_test_data).sum())
print("Gradient boosting: Total:", len(processed_test_data), "Survived:", gb_model.predict(processed_test_data).sum())
print("AdaBoost: Total:", len(processed_test_data), "Survived:", ab_model.predict(processed_test_data).sum())

processed_test_data_xgboost = processed_test_data.rename(columns=clean_col)
print("XGboost: Total:", len(processed_test_data), "Survived:", xgboost_model.predict(processed_test_data_xgboost).sum())

processed_test_data_float  = features_test.values.astype("float32")
y_pred_proba_nn = model.predict(processed_test_data_float)
y_pred_nn = (y_pred_proba > 0.5).astype(int)
print("Neural Network: Total:", len(processed_test_data), "Survived:", len(y_pred_nn))

What other models think, how many passengers survived Titanic from test set:
Logistic regression: Total: 418 Survived: 142
Decision tree: Total: 418 Survived: 140
Naive Bayes: Total: 418 Survived: 182
SVM: Total: 418 Survived: 61
SVM (winner): Total: 418 Survived: 151
Random forest: Total: 418 Survived: 140
Gradient boosting: Total: 418 Survived: 150
AdaBoost: Total: 418 Survived: 156
XGboost: Total: 418 Survived: 138
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
Neural Network: Total: 418 Survived: 179

I think from test set around 120-150 people survived on average